import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col antialiased">

        {/* Contenido principal */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Footer SIEMPRE abajo */}
        <footer className="border-t border-neutral-800 py-10 px-6">
          <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 items-center gap-6 text-sm text-gray-400">

            <div className="flex items-center gap-3">
              <img
                src="/wen-service.jpeg"
                alt="Wen Service"
                className="w-8 h-8 rounded"
              />
              <div>
                <p className="font-semibold text-white">Wen Service</p>
                <p>© 2025 Wen Service. Todos los derechos reservados.</p>
              </div>
            </div>

            <div className="md:text-right">
              <p>Contacto: hola@wenservice.cl</p>
              <p>+56 9 0000 0000</p>
            </div>

          </div>
        </footer>

      </body>
    </html>
  )
}
